### ISSUE TITLE
IE11 strict模式下不允许一个属性有多个定义

### ISSUE THREAD

**Issue by yanghao1351** [kevinongko/vue-numeric#25]
<vue-numeric name= "specObj.unitPrice" type="text" currency="¥" separator="," v-model="specObj.unitPrice"  v-bind:precision="2" min="0" v-bind:max="99999999" class="form-control addCommodity_shopper"></vue-numeric>

IE11 strict模式下不允许一个属性有多个定义

**Comment by kevinongko** [comment]
Hi @yanghao1351 ,

I don't understand Mandarin 😢

**Comment by pnzz7** [comment]
I think he ment that the plugin is not working with IE11.
I had the same issue. I'll send you the accurate error message later

**Comment by ra-dharma** [comment]
Hi kevinongko,

Thanks for an excellent plugin. 

I've implemented this in a variety of forms in my application. It works perfect in Chrome/Firefox browsers. But getting the following error in IE11. Can you please help with ?

SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: vue-numeric, Line: 1, Column: 4665

in this line - domProps:{value:e.value,value:e.amount}

Thanks, D

**Comment by te1** [comment]
The problem seems to be the `:value="value"` binding. If remove this the generated render function contains `domProps: { value: _vm.amount }` as expected and it works in IE. I have not found any negative side effects.

From https://vuejs.org/v2/guide/forms.html#Basic-Usage:
> v-model will ignore the initial `value`, `checked` or `selected` attributes found on any form elements.

It seems that the binding is not needed and instead you should do `this.amount = this.value` which happens in `mounted` anyway as far as I can tell.

Hope this helps.

**Comment by kevinongko** [comment]
Thanks for the suggestion and error messages guys, the plugin should work now in v2.2.2
