### ISSUE TITLE
Error when you define 8 o more decimals

### ISSUE THREAD

**Issue by jamiguel** [kevinongko/vue-numeric#66]
## Expected Behavior
Value:  1000.00000000
Result: 1000.00000000

## Actual Behavior
Value:  1000.00000000
Result: 1000.00000001

You can try in the Live demo.

## Specifications

  - Plugin Version: v2.3.0
  - Vue.js Version: v2.5.3
  - Browser: any
  - OS: Windows 10

Thanks!

**Comment by csms0726** [comment]
Same for me. Any idea guys?

**Comment by kevinongko** [comment]
Seems like this is a bug with accounting-js lib, the same [issue](https://github.com/openexchangerates/accounting.js/issues/192) can be found here

**Comment by lucasgehl3n** [comment]
**Hello,**
If anyone is still experiencing this problem, I believe I have managed to resolve it.

The toFixed function (of the component) uses a technique of adding a theoretically insignificant value to the end of the number (1e-8). This is done so that rounding numbers like 2.22385, for example, are done to 2.2239, and not to 2.2238, avoiding problems with financial systems. However, the added value (1e-8) becomes significant when we work with many decimal places (when more than 7 are used). Thus, it is necessary that the sum realized is of an even smaller value instead of this, in order to accommodate a larger number of houses in the system (or to rethink the question of implementation for financial systems).

So, change `Math.Round((value + 1e-8) * power) / power).toFixed(precision) `   for  `Math.Round((value + 1e-31) * power) / power).toFixed(precision) `

**Comment by lucasgehl3n** [comment]
> Seems like this is a bug with accounting-js lib, the same [issue](https://github.com/openexchangerates/accounting.js/issues/192) can be found here

Hello,
If anyone still has the problem, I updated the thread mentioned above with the solution.
